// Emits cpp/include/masks.h from the simulator's own swept-footprint traces, so
// the firmware tests clearance against exactly the sub-cells the simulator
// does, with no geometry reimplemented on the C++ side.
//
//   bun cpp/tools/gen_tables.ts      (or: make -C cpp masks)
//
// The generated header is committed, because the robot is built by a toolchain
// that has no bun and no TypeScript. Nothing reruns this automatically —
// test/masks.test.ts compares the committed tables against the simulator and
// fails if the geometry has moved on without them.
//
// Each trace turns out to be row-convex: every row of every mask is a single
// unbroken run of sub-cells. That collapses 25kB of coordinate pairs into 336
// bytes of row spans, and lets a clearance test run one word comparison per row
// instead of one bit lookup per sub-cell. toRows() rejects the tables outright
// if a geometry change ever breaks that property, since a span keeps no record
// of a hole it swallowed and the firmware would silently start treating gaps as
// solid.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  FACING_EAST,
  FACING_NORTH,
  FULL_TURN,
  QUARTER_TURN,
  START_CLEAR_RADIUS_CM,
} from "../../src/robot/program";

interface Row {
  dy: number;
  xMin: number;
  xMax: number;
}

const OUTPUT = join(dirname(fileURLToPath(import.meta.url)), "../include/masks.h");

const MASKS: { name: string; offsets: Int16Array }[] = [
  { name: "FACING_NORTH", offsets: FACING_NORTH },
  { name: "FACING_EAST", offsets: FACING_EAST },
  { name: "QUARTER_TURN", offsets: QUARTER_TURN },
  { name: "FULL_TURN", offsets: FULL_TURN },
];

/**
 * Collapse packed (dx, dy) pairs into one span per row, ordered outwards from
 * the pivot's own row so that an obstacle beside the robot rejects on the first
 * few spans rather than after walking the whole mask.
 */
function toRows(name: string, offsets: Int16Array): Row[] {
  const spans = new Map<number, { xMin: number; xMax: number; count: number }>();
  for (let k = 0; k < offsets.length; k += 2) {
    const dx = offsets[k];
    const dy = offsets[k + 1];
    const span = spans.get(dy);
    if (!span) {
      spans.set(dy, { xMin: dx, xMax: dx, count: 1 });
      continue;
    }
    span.xMin = Math.min(span.xMin, dx);
    span.xMax = Math.max(span.xMax, dx);
    span.count++;
  }

  const rows: Row[] = [];
  for (const [dy, span] of spans) {
    if (span.count !== span.xMax - span.xMin + 1) {
      throw new Error(
        `${name} row dy=${dy} is not one unbroken run: ${span.count} sub-cells ` +
          `spanning [${span.xMin}, ${span.xMax}]. The row-span encoding cannot ` +
          `represent this mask.`,
      );
    }
    if (span.xMin < -128 || span.xMax > 127 || dy < -128 || dy > 127) {
      throw new Error(`${name} row dy=${dy} does not fit in int8_t`);
    }
    rows.push({ dy, xMin: span.xMin, xMax: span.xMax });
  }

  rows.sort((a, b) => Math.abs(a.dy) - Math.abs(b.dy) || a.dy - b.dy);
  return rows;
}

function emitMask(name: string, rows: Row[], cells: number): string {
  return [
    `// ${cells} sub-cells in ${rows.length} rows.`,
    `const Row ${name}_ROWS[${rows.length}] = {`,
    rows.map((r) => `    {${r.dy}, ${r.xMin}, ${r.xMax}},`).join("\n"),
    `};`,
    `const Mask ${name} = {${name}_ROWS, ${rows.length}};`,
  ].join("\n");
}

const bodies = MASKS.map(({ name, offsets }) =>
  emitMask(name, toRows(name, offsets), offsets.length / 2),
);

writeFileSync(
  OUTPUT,
  `#ifndef ROBOT_MASKS_H
#define ROBOT_MASKS_H

#include <stdint.h>

// Generated by cpp/tools/gen_tables.ts. Do not edit by hand; run
// \`make -C cpp masks\` instead. test/masks.test.ts fails if this file and the
// simulator's footprint geometry disagree.
//
// The sets of sub-cells the robot's body sweeps through while holding or
// changing heading, as one span per row measured from the pivot's sub-cell.
// The masks nest: a full turn contains a quarter turn, which contains both
// fixed headings.

namespace masks {

struct Row {
  int8_t dy;
  int8_t xMin;
  int8_t xMax;
};

struct Mask {
  const Row* rows;
  uint8_t count;
};

// Cleared around the starting pose, which the robot is assumed to be able to
// spin freely within.
const double START_CLEAR_RADIUS_CM = ${START_CLEAR_RADIUS_CM};

${bodies.join("\n\n")}

}  // namespace masks

#endif  // ROBOT_MASKS_H
`,
);

const rows = MASKS.reduce((sum, m) => sum + toRows(m.name, m.offsets).length, 0);
console.log(`wrote ${OUTPUT}: ${rows} rows, ${rows * 3} bytes of mask tables`);
